baseurl: https://yukis-blog.netlify.app
DefaultContentLanguage: en
title: YuKi's Blog
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon.ico
  logo: /img/black_rose.png
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: yes
  showRelatedPosts: yes
  socialShare: yes
  subtitle: 真话不全说，假话全不说，只好说废话
  useHLJS: yes
  wordCount: yes
Author:
  500px: username
  bandcamp: username
  bitbucket: username
  codepen: username
  discord: invite code (https://discord.gg/XXXXXXX)
  email: hmz1969a@gmail.com
  facebook: username
  github: sinnyuki
  gitlab: username
  instagram: sinnyuki
  itchio: username
  kaggle: username
  linkedin: username
  mastodon: url
  name: YuKi
  paypal: username
  reddit: yuki961004
  slack: username
  snapchat: username
  soundcloud: username
  spotify: username
  stackoverflow: users/XXXXXXX/username
  strava: userid
  telegram: username
  twitter: YuKi64810517
  vk: username
  website: yourwebsite.com
  weibo: username
  xing: username
  youtube: user/username
menu:
  main:
    - name: Blog
      url: ''
      weight: 1
    - identifier: categories
      name: Categories
      pageref: categories/
      weight: 2
    - name: About
      url: page/about/
      weight: 3   
    - name: Tags
      url: tags
      weight: 4

